### ISSUE TITLE
Internationalization Support for Post Status Display

### ISSUE THREAD

**Issue by huubl** [andyexeter/post-lockdown#14]
I suggest enhancing the status column class to support multiple languages. Currently, the status (Locked or Protected) is displayed using [hardcoded](https://github.com/andyexeter/post-lockdown/blob/4a119607c2c00dd958cef5f356c1af6f5db9fcce/src/PostLockdown/StatusColumn.php#L122-L130) English strings.

Pull request:
https://github.com/andyexeter/post-lockdown/pull/15

**Comment by andyexeter** [comment]
Fixed by #15
