### ISSUE TITLE
Function _load_textdomain_just_in_time was called incorrectly.

### ISSUE THREAD

**Issue by huubl** [andyexeter/post-lockdown#18]
Hi @andyexeter,

Since WordPress 6.7 the plugin throws a notice error:
`Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the post-lockdown domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later. (This message was added in version 6.7.0.)`

I think adding `$this>bulk_actions` to the `init` or `admin_init` hook will solve the issue.
https://github.com/andyexeter/post-lockdown/blob/e2b68a9c0b005a84d8626aa46705872c060ab336/src/PostLockdown/BulkActions.php#L15-L20

**Comment by andyexeter** [comment]
Hi @huubl,

Thanks for reporting this.

I think we can probably just move the array into the `_add_bulk_actions` method and remove the class property. I will try and get something released this week :)

**Comment by andyexeter** [comment]
Hi @huubl,

I have just released v4.0.2 of the plugin which contains a fix for this.

**Comment by huubl** [comment]
> Hi @huubl,
> 
> I have just released v4.0.2 of the plugin which contains a fix for this.

Awesome, thanks!
