### ISSUE TITLE
Support for large number of posts

### ISSUE THREAD

**Issue by joshuadavidnelson** [andyexeter/post-lockdown#4]
Thanks for this great plugin! While attempting to get this to work on a site with a huge amount of content I ran into memory capacity fatal errors trying to load the Post Lockdown options page. This appeared to be related to the `get_posts` function query...

Using the `postlockdown_get_posts` filter and added the following query arguments to resolve the issue:

```php
/**
 * Filter the post query to avoid fatal errors.
 */
function filter_post_args( $args = array() ) {

	$args['posts_per_page'] = 100;
	$args['update_post_term_cache'] = false;
	$args['update_post_meta_cache'] = false;
	$args['no_found_rows'] = true;
	$args['ignore_sticky_posts'] = true;

	return $args;
}
```

I think the key items were the `posts_per_page`, `update_post_term_cache`, and `update_post_meta_cache` parameters. Perhaps something to be added to the core of the plugin? I can put a PR together if you think it's worthwhile.

**Comment by andyexeter** [comment]
Thanks for the feedback :smile: 

We only fetch 10 posts at a time, so I don't believe setting `posts_per_page` to 100 is helping here:

https://github.com/andyexeter/post-lockdown/blob/61bfdcd012790fdd3a01e71e72964937fdacdeb1/src/PostLockdown/OptionsPage.php#L85-L94

Could you remove `posts_per_page` from your filter function and confirm?

The `update_post_meta_cache` and `update_post_term_cache` parameters look interesting though, as well as `no_found_rows`. 

I'd like to make sure that setting them won't cause any unknown side-effects first, but if we are able to set them all then this would provide a nice performance boost and is something I'd happily accept a PR for.

**Comment by joshuadavidnelson** [comment]
Hey there! It appears like the issue I was encountering was actually related to some custom post types (we have quite a few on this site), and using your post type filter fixed the issue. (What I didn't show in my first comment was the `post_type` parameter I was originally setting in the query filter, which essentially did the same thing)

That said, I did see some improvement by adding the `update_post_meta_cache`, `update_post_term_cache`, and `no_found_rows` arguments. Query monitor showed it dropped at least 8 queries from the admin pages initial load, I didn't test the ajax queries, but I would imagine it's the same for those.

It looks like you're storing the locked/protected post ids in a site option, so you don't need any post meta or taxonomy information from the queries and should be safe to use those parameters ([codex link for quick reference](https://developer.wordpress.org/reference/classes/wp_query/#caching-parameters)).

Looking back at that codex documentation, we might also gain some performance from adding `cache_results => false`?

Let me know if you think it's worthwhile, happy to put a PR together.

**Comment by andyexeter** [comment]
PR sounds great, thank you!

Let's get cache_results => false in there too 👍
